from environs import Env

env = Env()
env.read_env()

SQLALCHEMY_DATABASE_USER = env.str('SQLALCHEMY_DATABASE_USER', "glitch")
SQLALCHEMY_DATABASE_PASSWORD = env.str('SQLALCHEMY_DATABASE_PASSWORD', "password")
SQLALCHEMY_DATABASE_NAME = env.str('SQLALCHEMY_DATABASE_NAME', "db")
SQLALCHEMY_DATABASE_HOST = env.str('SQLALCHEMY_DATABASE_HOST', "localhost")
SQLALCHEMY_DATABASE_PORT = env.int('SQLALCHEMY_DATABASE_PORT', 5432)
SQLALCHEMY_DATABASE_URL = f"postgresql://{SQLALCHEMY_DATABASE_USER}:{SQLALCHEMY_DATABASE_PASSWORD}@{SQLALCHEMY_DATABASE_HOST}:{SQLALCHEMY_DATABASE_PORT}/{SQLALCHEMY_DATABASE_NAME}"
