from environs import Env

env = Env()
env.read_env()

SQLALCHEMY_DATABASE_USER = env.str('SQLALCHEMY_DATABASE_USER', "user")
SQLALCHEMY_DATABASE_PASSWORD = env.str('SQLALCHEMY_DATABASE_PASSWORD', "password")
SQLALCHEMY_DATABASE_NAME = env.str('SQLALCHEMY_DATABASE_NAME', "db")
SQLALCHEMY_DATABASE_URL = f"postgresql://{SQLALCHEMY_DATABASE_USER}:{SQLALCHEMY_DATABASE_PASSWORD}@postgresserver/{SQLALCHEMY_DATABASE_NAME}"
